#!/bin/sh

# Run this file in a separate tab while running the integration tests.
# You can `brew install chromedriver` to get the executable on your $PATH.

# The BACKCHAT_DEBUG environment variable will be made accessible to
# server/main.js, in case it wants to do anything different to normal
# (eg: running using test fixtures, rather than live data).

BACKCHAT_DEBUG=True chromedriver
