#!/usr/bin/env node

var ircd = require('ircdjs');

// ircd.winston.remove(ircd.winston.transports.Console);

var server = new ircd.Server();

server.config = {
  network:  "ircn",
  hostname: "localhost",
  serverDescription: "A Node IRC daemon",
  serverName: "server1",
  port: 6667,
  whoWasLimit: 10000,
  idleTimeout: 60,
  opers: {},
  channels: {
    '#channel1': { topic: "Welcome to Channel 1" },
    '#channel2': { topic: "Second Channel" }
  }
}

server.start();
server.createDefaultChannels();
