#!/bin/sh

for filename in src/client/js/*.js; do
  if node_modules/.bin/acorn --silent $filename; then
    true
  else
    echo "^ Error in ${filename}"
    exit 1
  fi
done

for filename in src/server/*.js; do
  if node_modules/.bin/acorn --silent $filename; then
    true
  else
    echo "^ Error in ${filename}"
    exit 1
  fi
done
